name: Setup Dependencies

inputs:
  setup-node:
    description: Whether to setup Node.js and Yarn
    required: false
    default: true
  setup-go:
    description: Whether to setup Go
    required: false
    default: true
  go-working-directory:
    description: The working directory for Go
    required: false
    default: .
  node-working-directory:
    description: The working directory for Yarn
    required: false
    default: ./ui
  node-version:
    description: The version of Node.js to use
    required: false
    default: 20.x

runs:
  using: composite
  steps:
    - name: Setup Node.js
      if: ${{ inputs.setup-node }}
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.node-working-directory }}/yarn.lock

    - name: Install Yarn Dependencies
      if: ${{ inputs.setup-node }}
      working-directory: ${{ inputs.node-working-directory }}
      shell: bash
      run: |
        yarn install --immutable

    - name: Setup Go
      if: ${{ inputs.setup-go }}
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: ${{ inputs.go-working-directory }}/go.mod

    - name: Install Go Dependencies
      if: ${{ inputs.setup-go }}
      working-directory: ${{ inputs.go-working-directory }}
      shell: bash
      run: |
        go get .
