name: GoLang AIO CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Format Node
        working-directory: ./web
        run: yarn format

      - name: Format Go
        run: |
          gofmt_output=$(gofmt -s -d .)
          if [ -n "$gofmt_output" ]; then
            echo "Code formatting issues found:"
            echo "$gofmt_output"
            exit 1
          fi


  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint Node
        working-directory: ./web
        run: yarn lint

      - name: Analyze Go
        run: go vet ./...

      - name: Lint Go
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5
        with:
          version: latest
          skip-pkg-cache: true


  test:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps
        with:
          setup-node: false

      - name: Test Go
        run: go test -v ./...


  build-binary:
    runs-on: ubuntu-latest
    needs: [test, lint]
    strategy:
      fail-fast: false
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Build Node
        working-directory: ./web
        run: yarn export

      - name: Build Go
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o ./bin/golang-aio .
          sha256sum ./bin/golang-aio > ./bin/golang-aio-checksum

      - name: Upload Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: golang-aio-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./bin/golang-aio
            ./bin/golang-aio-checksum
          if-no-files-found: error


  build-docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Build Image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          context: .
          tags: golang-aio:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  fan-in:
    runs-on: ubuntu-latest
    needs: [format, lint, test, build-binary, build-docker]
    if: always()
    steps:
      - name: Check Jobs
        shell: bash
        env:
          JOBS: ${{ toJSON(needs) }}
        run: |
          echo "Job status:"
          echo $JOBS | jq -r 'to_entries[] | " - \(.key): \(.value.result)"'
          for i in $(echo $JOBS | jq -r 'to_entries[] | .value.result'); do
            if [ "$i" != "success" ] && [ "$i" != "skipped" ]; then
              echo ""
              echo "Status check not okay!"
              exit 1
            fi
          done
