name: GoLang AIO CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Format Node
        working-directory: ./ui
        run: yarn format --check

      - name: Format Go
        run: |
          gofmt_output=$(gofmt -s -d .)
          if [ -n "$gofmt_output" ]; then
            echo "Code formatting issues found:"
            echo "$gofmt_output"
            exit 1
          fi


  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint Node
        working-directory: ./ui
        run: yarn lint

      - name: Analyze Go
        run: go vet ./...

      - name: Lint Go
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Build Node
        working-directory: ./ui
        run: yarn export

      - name: Build Go
        run: go build -o ./bin/golang-aio-ci .
