name: GoLang AIO CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Format Node
        working-directory: ./web
        run: yarn format

      - name: Format Go
        run: |
          gofmt_output=$(gofmt -s -d .)
          if [ -n "$gofmt_output" ]; then
            echo "Code formatting issues found:"
            echo "$gofmt_output"
            exit 1
          fi


  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint Node
        working-directory: ./web
        run: yarn lint

      - name: Analyze Go
        run: go vet ./...

      - name: Lint Go
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v6
        with:
          version: latest
          skip-pkg-cache: true


  test:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps
        with:
          setup-node: false

      - name: Test Go
        run: go test -v ./...


  build-binary:
    runs-on: ubuntu-latest
    needs: [test, lint]
    strategy:
      fail-fast: false
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Build Node
        working-directory: ./web
        run: yarn export

      - name: Build Go
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o ./bin/golang-aio .
          sha256sum ./bin/golang-aio > ./bin/golang-aio-checksum

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: golang-aio-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./bin/golang-aio
            ./bin/golang-aio-checksum
          if-no-files-found: error


  build-docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Build Image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          tags: golang-aio:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  fan-in:
    runs-on: ubuntu-latest
    needs: [format, lint, test, build-binary, build-docker]
    if: always()
    steps:
      - name: Check Jobs
        shell: bash
        env:
          JOBS: ${{ toJSON(needs) }}
        run: |
          echo "Job status:"
          echo $JOBS | jq -r 'to_entries[] | " - \(.key): \(.value.result)"'
          for i in $(echo $JOBS | jq -r 'to_entries[] | .value.result'); do
            if [ "$i" != "success" ] && [ "$i" != "skipped" ]; then
              echo ""
              echo "Status check not okay!"
              exit 1
            fi
          done
