name: GoLang AIO CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint Node
        working-directory: ./ui
        run: yarn lint

      - name: Lint Go
        run: go fmt ./... && go vet ./...


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-deps

      - name: Build Node
        working-directory: ./ui
        run: yarn export

      - name: Build Go
        run: go build -o ./bin/golang-aio-ci .
