name: Renovate

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/renovate.json5"
      - "renovate.json"
      - "renovate.json5"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
