name: Security

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at 00:00 UTC

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4
        with:
          # Since this is a personal project, and not intended to be used in production
          # I am failing on high and critical errors.  Normally, this would be low or
          # moderate
          fail-on-severity: high


  secrets-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@433a57adaf8fedce312630ef593f5142227c5855 # v3.78.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified


  codeql-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go', 'javascript-typescript' ]
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      # CodeQL uses an older version of Go than the project requires
      - name: Setup Go
        if: ${{ matrix.language == 'go' }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: ./go.mod

      - name: Initialize CodeQL
        uses: github/codeql-action/init@530d4feaa9c62aaab2d250371e2061eb7a172363 # v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@530d4feaa9c62aaab2d250371e2061eb7a172363 # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@530d4feaa9c62aaab2d250371e2061eb7a172363 # v3
        with:
          category: "/language:${{matrix.language}}"
