name: Security

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@01bc87099ba56df1e897b6874784491ea6309bc4 # v3
        with:
          # Since this is a personal project, and not intended to be used in production
          # I am failing on high and critical errors.  Normally, this would be low or
          # moderate
          fail-on-severity: high
