name: Security

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at 00:00 UTC

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4
        with:
          # Since this is a personal project, and not intended to be used in production
          # I am failing on high and critical errors.  Normally, this would be low or
          # moderate
          fail-on-severity: high


  secrets-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@ded5f45b92c00939718787ce586b520bbe795f3b # v3.88.18
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified


  codeql-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go', 'javascript-typescript' ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # CodeQL uses an older version of Go than the project requires
      - name: Setup Go
        if: ${{ matrix.language == 'go' }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: ./go.mod

      - name: Initialize CodeQL
        uses: github/codeql-action/init@5f8171a638ada777af81d42b55959a643bb29017 # v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@5f8171a638ada777af81d42b55959a643bb29017 # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@5f8171a638ada777af81d42b55959a643bb29017 # v3
        with:
          category: "/language:${{matrix.language}}"
